data_files:
    ALDOB: MPRA/Patwardhan_SupplementaryData/trivariate.tab
    ECR11: MPRA/Patwardhan_SupplementaryData/trivariate.tab
    BCL11A: MPRA/GRCh38_ALL.tsv
    F9: MPRA/GRCh38_ALL.tsv
    FOXE1: MPRA/GRCh38_ALL.tsv
    GP1BA: MPRA/GRCh38_ALL.tsv
    HBB: MPRA/GRCh38_ALL.tsv
    HBG1: MPRA/GRCh38_ALL.tsv
    HNF4A: MPRA/GRCh38_ALL.tsv
    IRF4: MPRA/GRCh38_ALL.tsv
    IRF6: MPRA/GRCh38_ALL.tsv
    LDLR: MPRA/GRCh38_ALL.tsv
    LDLR.2: MPRA/GRCh38_ALL.tsv
    MSMB: MPRA/GRCh38_ALL.tsv
    MYCrs11986220: MPRA/GRCh38_ALL.tsv
    MYCrs6983267: MPRA/GRCh38_ALL.tsv
    PKLR-24h: MPRA/GRCh38_ALL.tsv
    PKLR-48h: MPRA/GRCh38_ALL.tsv
    RET: MPRA/GRCh38_ALL.tsv
    SORT1: MPRA/GRCh38_ALL.tsv
    SORT1.2: MPRA/GRCh38_ALL.tsv
    SORT1-flip: MPRA/GRCh38_ALL.tsv
    TCF7L2: MPRA/GRCh38_ALL.tsv
    TERT-GAa: MPRA/GRCh38_ALL.tsv
    TERT-GBM: MPRA/GRCh38_ALL.tsv
    TERT-GSc: MPRA/GRCh38_ALL.tsv
    TERT-HEK: MPRA/GRCh38_ALL.tsv
    UC88: MPRA/GRCh38_ALL.tsv
    ZFAND3: MPRA/GRCh38_ALL.tsv
    ZRSh-13: MPRA/GRCh38_ALL.tsv
    ZRSh-13h2: MPRA/GRCh38_ALL.tsv

data_styles:
    ALDOB: patwardhan
    ECR11: patwardhan
    BCL11A: kirchner
    F9: kirchner
    FOXE1: kirchner
    GP1BA: kirchner
    HBB: kirchner
    HBG1: kirchner
    HNF4A: kirchner
    IRF4: kirchner
    IRF6: kirchner
    LDLR: kirchner
    LDLR.2: kirchner
    MSMB: kirchner
    MYCrs11986220: kirchner
    MYCrs6983267: kirchner
    PKLR-24h: kirchner
    PKLR-48h: kirchner
    RET: kirchner
    SORT1: kirchner
    SORT1.2: kirchner
    SORT1-flip: kirchner
    TCF7L2: kirchner
    TERT-GAa: kirchner
    TERT-GBM: kirchner
    TERT-GSc: kirchner
    TERT-HEK: kirchner
    UC88: kirchner
    ZFAND3: kirchner
    ZRSh-13: kirchner
    ZRSh-13h2: kirchner


promoters : [
    TERT-GAa, TERT-GBM, TERT-GSc, TERT-HEK, LDLR, LDLR.2, HBB, HBG1, HNF4A,
    MSMB, PKLR-24h, PKLR-48h, F9, FOXE1, GP1BB
]

enhancers: [
    SORT1, SORT1.2, SORT1-flip ZRSh-13, ZRSh-13h2, BCL11A, IRF4, IRF6,
    MYCrs6983267, MYCrs11986220, RET, TCF7L2, ZFAND3, UC88
]
